DROP DATABASE IF EXISTS DB_FITOFITO;
CREATE DATABASE DB_MAPAS;
USE DB_MAPAS;
DROP TABLE IF EXISTS ATLETAS
CREATE TABLE ATLETAS ( 
            ID_ATLETA VARCHAR(6) NOT NULL,
		    AUTH_CODE DATE,
			HORA TIME,
			PRECIO DECIMAL(5,2),
			LOCALIZACION VARCHAR(100),
			PLAZAS INT(11),
			PRIMARY KEY (ID_EVENTO))
	ENGINE= InnoDB;